### PR TITLE
Update to Unicode 15.0

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Review by alerque — APPROVED** [review]

**Comment by alerque** [comment]
Thanks far contributing this.

Also I'd like to gently poke the maintainer, as the Unicode 14 commit hasn't been put out in a stable release tag yet. After this merges can we get a release to make downstream project management easier? Thanks.

**Comment by starwing** [comment]
OK👌🏻thanks for the contribution. I will make a release this weekend

**Comment by SlySven** [comment]
Ah, that will address my comment: https://github.com/starwing/luautf8/issues/32#issuecomment-1250955460 ! :grinning:

**Comment by starwing** [comment]
I have update the luarocks

**Pull request merged**
