### PR TITLE
Add new 'grapheme_indices' function

### PR DESCRIPTION
**Pull request by alexdowad**
This new function allows `luautf8` to be used for Unicode grapheme segmentation. Discussion is in #46.

Thanks to @Erutuon for suggesting the API for the new function.

I think I've covered all my bases; documentation, adding tests, etc.

### CODE REVIEW

**Comment by alexdowad** [comment]
Just added another test case to `test.lua`.

**Comment by starwing** [comment]
@alexdowad is there any questions for comments?

**Comment by starwing** [comment]
@alexdowad there are two comments in code, you could see whether they need fixed.

**Comment by alexdowad** [comment]
> @alexdowad there are two comments in code, you could see whether they need fixed.

OK, I'm sorry, @starwing, I didn't understand what you meant in your previous post.

Will look at your comments. Thanks very much.

**Comment by alexdowad** [comment]
@starwing, I can't find your comments. Could you please share them again?

**Comment by starwing** [comment]
@alexdowad here:
image

**Comment by alexdowad** [comment]
Thanks so much, just looking into those good comments...

**Comment by alexdowad** [comment]
I have amended the code to use `byte_relat` and to throw errors on invalid values of the `start` and `end` arguments.

**Comment by alexdowad** [comment]
@starwing Your comment about the code which handles sequences of Indic "extend", "linker", and "consonant" codepoints is also very correct. I have amended the code accordingly.

**Pull request merged**
